theme = "fleet_dark"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
"C-[" = "goto_previous_buffer"
"C-]" = "goto_next_buffer"
A-w = ":buffer-close"
# Nushell does not support suspend: https://github.com/helix-editor/helix/discussions/10545
C-z = "no_op"

[keys.select]
C-z = "no_op"

[keys.normal."\\"]
t = ":sh hxextra terminal"
k = ":sh hxextra kill"
g = ":sh hxextra lazygit"
b = ":sh hxextra blame"
r = ":sh hxextra repl"
s = ":pipe-to hxextra send"

[keys.select."\\"]
t = ":sh hxextra terminal"
k = ":sh hxextra kill"
g = ":sh hxextra lazygit"
b = ":sh hxextra blame"
r = ":sh hxextra repl"
s = ":pipe-to hxextra send"

[editor]
shell = ["nu", "-c"]
