[[language]]
name = "starlark"
file-types = [
  "bzl",
  "bazel",
  "star",
  { glob = "BUILD" },
  { glob = "BUILD.*" },
  { glob = "Tiltfile" },
  { glob = "WORKSPACE" },
]
# language-servers = ["buck2"]
language-servers = ["starpls"]
formatter = { command = "buildifier", args = ["-"] }
auto-format = true

[language-server.starpls]
args = []
command = "starpls"

[language-server.buck2]
command = "buck2"
args = ["lsp"]

[language-server.java-language-server]
command = "java-language-server"

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "java"
language-servers = ["java-language-server"]

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.taplo.config]
# Workaround for nonsense of being nonfunctional outside git directories
# (https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437)
root_dir = [".git", "*.toml"]

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
args = ["--stdio"]
config = { provideFormatter = true, json = { validate = { enable = true } } }

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
